### ISSUE TITLE
I am just wondering if generator and discriminator has 1:5 update

### ISSUE THREAD

**Issue by jimlinntu** [fairytale0011/Conditional-WassersteinGAN#3]
As the title, I have already seen your code, but I think that your generator and discriminator are not roughly 1:5 updates. (I think it is something like 1:7 updates for generator and discriminator?)
Could you please explain it me? 
Thanks.

**Comment by fairytale0011** [comment]
See https://github.com/fairytale0011/Conditional-WassersteinGAN/issues/2#issuecomment-356752239. Basically vanilla WGAN is unstable, WGAN-GP is much better.

**Comment by jimlinntu** [comment]
I just saw the original [WGAN implementation](https://github.com/martinarjovsky/WassersteinGAN), but I didn't see any variable like your "c_interv"  variable.
Could you post the code where you find this hack?

**Comment by fairytale0011** [comment]
It does not exist in the original WGAN implementation, because WGAN does not have a classifier. I added it in myself to train the generator twice on the classifier every around 7 discriminator iterations.
